# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: t3r1jj/fcms:0.0.2
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false

    working_directory: ~/repo

    steps:
      - checkout

      - run: chmod +x ./gradlew

      - run:
          name: Hash dependency info
          command: |
            mkdir -p build
            md5sum gradle/wrapper/gradle-wrapper.properties build.gradle > build/deps.md5
      - restore_cache:
          key: gradle-{{ checksum "build/deps.md5" }}

      - run: ./gradlew build

      - save_cache:
          key: gradle-{{ checksum "build/deps.md5" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit
            mkdir -p ~/artifacts
            find . -type f -regex ".*/build/test-results/*/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/artifacts
          destination: build/libs

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: build/libs
          # Must be relative path from root
          paths: .

  deploy:
    docker:
      - image: t3r1jj/fcms:0.0.2

    environment:
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false

    working_directory: ~/repo

    steps:
      - checkout

      - run: chmod +x ./gradlew

      - attach_workspace:
          at: build/libs

      - run:
          name: Deploy if build pass and branch is naster with version tag
          command: ./gradlew bintrayUpload -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only:
                - /^v\d+\.\d+\.\d+$/
            branches:
              only: master